- api/src/lib/xdomainRoute.js
- api/src/server.js
- config/default.js
- makefile
- package.json
> [RFR] API security improvment

- app/admin/css/login.scss
- app/admin/index.html
- app/admin/login.html
- app/frontend/css/main.scss
- app/frontend/index.html
- app/mobile/css/main.scss
- app/mobile/index.html
- makefile
- package.json
- webpack/loaders.js
- webpack/mobile.config.js
- webpack/plugins.js
> [RFR] improvements based on @jpetitcolas comments on #9

- .babelrc
- api/src/admin.js
- api/src/api.js
- api/src/middlewares/tokenChecker.js
- api/src/server.js
- api/src/users/authenticateRoutes.js
- api/src/users/userModel.js
- bin/createAdmin.js
- config/development-dist.js
- config/production-dist.js
- config/test-dist.js
- makefile
> [RFR] Authentication for api (admin/api)

- api/src/admin.js
- api/src/orders/orderAdminApiRoutes.js
- api/src/products/productAdminApiRoutes.js
- api/src/server.js
- app/admin/js/main.js
- app/admin/js/orders/config.js
- app/admin/js/products/config.js
- config/default.js
- webpack/plugins.js
> [RFR] Product and Order admin

- config/default.js
- config/test-dist.js
- src/api/server.js
- src/api/users/authenticateRoutes.js
- src/api/users/rateLimiter.js
> [RFR] Improve security

- e2e/api/public/api.js
- e2e/api/public/apiAuthenticate.js
- e2e/api/public/apiOrders.js
- e2e/api/public/apiOrdersId.js
- e2e/api/public/apiProducts.js
- e2e/api/public/apiProductsId.js
Thanks @jeromemacias for the tip
> [RFR] Using response body as test fail explanation

- e2e/api/public/api.js
- e2e/api/public/apiAuthenticate.js
- e2e/api/public/apiOrders.js
- e2e/api/public/apiOrdersId.js
- e2e/api/public/apiProducts.js
- e2e/api/public/apiProductsId.js
The test comment must be a `string`, but body is a `json`object.
> [RFR] Body was display as an [Object Object]

- .gitignore
- src/frontend/js/user/SignIn.js
- src/frontend/js/user/SignUp.js
- src/frontend/js/user/redirectIfNotAuthenticated.js
- src/frontend/js/user/userActions.js
- src/frontend/js/user/userActions.spec.js
- src/frontend/js/user/userApi.js
- src/frontend/js/user/userReducer.js
- src/frontend/js/user/userReducer.spec.js
- src/frontend/js/user/userRoutes.js
- src/frontend/js/user/userSagas.js
- src/frontend/js/user/userSagas.spec.js
And cleaned up some names for more coherence
> [RFR] Added Frontend sign-up

- README.md
> [RFR] Readme

- README.md
> [RFR] Add a tip to explain how to change API port

- src/api/lib/db/queries/selectPage.js
> [RFR] Add default limit and offset for `selectPage` method

- src/admin/js/main.js
- src/admin/js/products/config.js
> [RFR] Fix ng-admin filter

- webpack/loaders.js
Now you can add static image with:
```js
render() {
return <img src={require('./hero_dog.jpg')} alt={'Hero Dog'} />;
}
```
> [RFR] Webpack image loader

- config/default.js
- config/development-dist.js
- config/production-dist.js
- config/test-dist.js
- package.json
- src/api/api.js
- src/api/lib/rateLimiter/memory.js
- src/api/lib/rateLimiter/null.js
- src/api/lib/rateLimiter/redis.js
All environments have been tested locally
> [RFR] Uses marmelab fork for koa-ratelimit

- .eslintrc
Otherwise some false positives could be thrown (fe react error in a node script)
> [RFR] Add missing env.

- src/frontend/js/app/entities/sagas.js
- src/frontend/js/order/orderSagas.js
- src/frontend/js/order/orderSagas.spec.js
- src/frontend/js/product/productSagas.js
- src/frontend/js/product/productSagas.spec.js
- src/frontend/js/user/userSagas.js
- src/frontend/js/user/userSagas.spec.js
Rewritten following the documentation to use `takeLatest`.
> [RFR] Rewrite sagas

- src/api/server.js
> [RFR] Add handler for node unhandled promise rejections

- .eslintrc
- src/frontend/js/app/App.js
- src/frontend/js/app/RouteTransition.js
- src/frontend/js/app/routes.js
- src/frontend/js/order/NewOrder.js
- src/frontend/js/order/NewOrderItem.js
- src/frontend/js/order/OrderItem.js
- src/frontend/js/order/OrderProductItem.js
- src/frontend/js/order/OrderStatusBadge.js
- src/frontend/js/product/ProductDetails.js
- src/frontend/js/product/ProductItem.js
- src/frontend/js/shoppingcart/ShoppingCart.js
- src/frontend/js/shoppingcart/ShoppingCartItem.js
- src/frontend/js/shoppingcart/shoppingCartActions.js
- src/frontend/js/shoppingcart/shoppingCartReducer.js
- src/frontend/js/shoppingcart/shoppingCartReducer.spec.js
- src/frontend/js/user/SignIn.js
- src/frontend/js/user/SignUp.js
- src/frontend/js/user/redirectIfNotAuthenticated.js
- src/frontend/js/user/userActions.spec.js
- src/frontend/js/user/userApi.js
- src/frontend/js/user/userReducer.js
> [RFR] Linting Frontend (Follow #94)

- src/admin/js/main.js
- src/api/lib/crud.js
> [RFR] Handle ngadmin list parameters without transformation client side

- config/default.js
- config/test-dist.js
- e2e/lib/request.js
- npm-shrinkwrap.json
- src/api/healthcare/api.js
- src/api/healthcare/api.spec.js
- src/api/healthcare/db.spec.js
- src/api/healthcare/internet.spec.js
- src/api/server.js
> [RFR] Fix CORS allow-origin

- package.json
- src/frontend/js/app/entities/fetchEntities.js
- src/frontend/js/app/entities/fetchEntities.spec.js
- src/frontend/js/app/entities/sagas.js
- src/frontend/js/app/entities/sagas.spec.js
- src/frontend/js/order/api.js
- src/frontend/js/product/api.js
> [RFR] Redux without profanity - step 2 (Follow #105)

- .travis.yml
- README.md
- makefile
> [RFR] Clean makefile and travis.yml

- .fabricrc-production
- .fabricrc-staging
- .travis.yml
- README.md
- doc/DEPLOY.md
- fabfile.py
- makefile
Follow #135 
No more `deploy-[environment]' targets, just specify `NODE_ENV` to target the correct environment
> [RFR] Simplify makefile using environment variables

- README.md
- package.json
- src/admin/index.html
- src/admin/js/user/sagas.js
- src/admin/webpack.config.babel.js
- Admin did not works at first install (`quill` was not installed and it missed a css loader for it) Fix #133
- There was an ugly margin around the admin
- An error was threw if the admin credentials was incorrect (there no error then but still no error message)
- The README was out of date
> [RFR] Make it works at first install

- makefile
- package.json
- src/api/healthcare/api.spec.js
- src/api/healthcare/db.js
- src/api/healthcare/db.spec.js
- src/api/healthcare/internet.spec.js
- src/api/lib/mails/sendEmails.spec.js
- src/api/lib/middlewares/pgCrud.spec.js
- src/api/users/userModel.spec.js
- src/frontend/e2e/_setup.js
- src/frontend/e2e/products.js
- yarn.lock
As we use `async/await`, we should be able to remove `co-mocha` from tests ...
> [RFR] Remove co-mocha from tests

- makefile
- src/admin/e2e/_setup.js
- src/admin/e2e/authentication.js
- src/admin/js/user/SignIn.js
- src/frontend/e2e/_setup.js
- src/frontend/e2e/products.js
> [RFR] Bootstraped admin e2e tests
